//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.nucleo.entities;

import java.io.Serializable;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Embeddable
@Getter
@Setter
@RequiredArgsConstructor
public class Proad implements Serializable{

    @NotNull(message = "Numero de protocolo não pode ser nulo.")
    private Integer protocoloNumero;
    
    @NotNull(message="Ano de protocolo não pode ser nulo.")
    private Integer protocoloAno;

    @Override
    public String toString() {
        if(null == getProtocoloAno() || null ==getProtocoloAno()){
            return "NULO";
        }
        return getProtocoloNumero().toString().concat("/").concat(getProtocoloAno().toString());
    }
    
    
}
